import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Privacy Policy - IconicMe AI Image Toy Maker",
  description: "Privacy policy for IconicMe - AI-powered image toy maker. Learn how we collect, use, and protect your data when creating custom plush toys and figurines.",
  openGraph: {
    title: "Privacy Policy - IconicMe",
    description: "Learn how iconicme protects your privacy while creating custom toys",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
  },
};

interface SectionProps {
  title: string;
  children: React.ReactNode;
}

const Section: React.FC<SectionProps> = ({ title, children }) => (
  <section className="mb-8">
    <h2 className="text-2xl font-semibold text-gray-800 mb-4 border-b border-gray-200 pb-2">
      {title}
    </h2>
    <div className="text-gray-700 leading-relaxed space-y-3">
      {children}
    </div>
  </section>
);

const PrivacyPolicyPage: React.FC = () => {
  const lastUpdated = "January 15, 2025";

  return (
    <div className="min-h-screen bg-gray-50">
        {/* Header */}
        <header className="bg-white shadow-sm border-b">
          <div className="max-w-4xl mx-auto px-4 py-6">
            <div className="flex items-center space-x-4">
              <img 
              src="/prod-logo.png"
              alt="IconicMe Logo" 
              className="w-10 h-10 rounded-xl object-contain"
            />
              <div>
                <h1 className="text-3xl font-bold text-gray-900">Privacy Policy</h1>
                <p className="text-gray-600">IconicMe - Image Stylizer</p>
              </div>
            </div>
          </div>
        </header>

        {/* Main Content */}
        <main className="max-w-4xl mx-auto px-4 py-8">
          <div className="bg-white rounded-lg shadow-sm p-8">
            {/* Last Updated */}
            <div className="mb-8 p-4 bg-blue-50 border border-blue-200 rounded-lg">
              <p className="text-sm text-blue-800">
                <strong>Last Updated:</strong> {lastUpdated}
              </p>
              <p className="text-sm text-blue-700 mt-1">
                This Privacy Policy is effective immediately for new users and will become effective on February 1, 2025 for existing users.
              </p>
            </div>

            {/* Introduction */}
            <Section title="Introduction">
              <p>
                Welcome to IconicMe, an AI-powered image stylization application developed by Pixelspulse Private Limited ("we," "our," or "us"). We are committed to protecting your privacy and ensuring the security of your personal information.
              </p>
              <p>
                This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile application IconicMe and our web service at https://iconicme.shop/ (collectively, the "Service").
              </p>
              <p>
                By using our Service, you consent to the data practices described in this policy. If you do not agree with this policy, please do not use our Service.
              </p>
            </Section>

            {/* Information We Collect */}
            <Section title="Information We Collect">
              <h3 className="text-lg font-semibold text-gray-800 mb-2">Personal Information</h3>
              <p>We may collect the following personal information when you use our Service:</p>
              <ul className="list-disc list-inside ml-4 space-y-2">
                <li>Email address (for account creation and authentication)</li>
                <li>User ID and authentication tokens (through Firebase)</li>
                <li>Subscription and payment information (processed through Lemon Squeezy)</li>
                <li>Device information (device type, operating system, app version)</li>
                <li>Usage analytics and app performance data</li>
              </ul>

              <h3 className="text-lg font-semibold text-gray-800 mb-2 mt-6">Image Data</h3>
              <ul className="list-disc list-inside ml-4 space-y-2">
                <li>Original images you upload for stylization</li>
                <li>Processed/stylized images generated by our AI models</li>
                <li>Image metadata (file size, format, timestamps)</li>
              </ul>

              <h3 className="text-lg font-semibold text-gray-800 mb-2 mt-6">Automatically Collected Information</h3>
              <ul className="list-disc list-inside ml-4 space-y-2">
                <li>IP address and geolocation data</li>
                <li>Browser type and version</li>
                <li>Pages visited and time spent in the app</li>
                <li>Crash reports and error logs</li>
              </ul>
            </Section>

            {/* How We Use Your Information */}
            <Section title="How We Use Your Information">
              <p>We use the collected information for the following purposes:</p>
              <ul className="list-disc list-inside ml-4 space-y-2">
                <li><strong>Service Provision:</strong> To process your images using FLUX.1 Kontext Pro AI models</li>
                <li><strong>Account Management:</strong> To create and maintain your user account</li>
                <li><strong>Payment Processing:</strong> To handle subscriptions and billing through our payment partners</li>
                <li><strong>Service Improvement:</strong> To analyze usage patterns and improve our AI models and user experience</li>
                <li><strong>Customer Support:</strong> To respond to your inquiries and provide technical assistance</li>
                <li><strong>Security:</strong> To detect, prevent, and address technical issues and fraudulent activities</li>
                <li><strong>Communication:</strong> To send service-related notifications and updates</li>
                <li><strong>Legal Compliance:</strong> To comply with applicable laws and regulations</li>
              </ul>
            </Section>

            {/* Image Processing and AI */}
            <Section title="Image Processing and AI">
              <h3 className="text-lg font-semibold text-gray-800 mb-2">AI Processing</h3>
              <p>
                Our Service uses FLUX.1 Kontext Pro, a third-party AI service provided by Black Forest Labs, to process and stylize your images. When you upload an image:
              </p>
              <ul className="list-disc list-inside ml-4 space-y-2">
                <li>Your images are temporarily transmitted to Black Forest Labs' servers for processing</li>
                <li>Images are processed according to Black Forest Labs' privacy policies and data handling practices</li>
                <li>We do not permanently store your original images on our servers</li>
                <li>Processed images are temporarily cached and then deleted after a reasonable period</li>
              </ul>

              <h3 className="text-lg font-semibold text-gray-800 mb-2 mt-6">Data Retention for Images</h3>
              <ul className="list-disc list-inside ml-4 space-y-2">
                <li>Original images: Deleted immediately after processing</li>
                <li>Processed images: Stored temporarily for download, then deleted within 24 hours</li>
                <li>Image metadata: May be retained for analytics purposes (anonymized)</li>
              </ul>
            </Section>

            {/* Data Sharing and Disclosure */}
            <Section title="Data Sharing and Disclosure">
              <p>We may share your information with the following third parties:</p>
              
              <h3 className="text-lg font-semibold text-gray-800 mb-2">Service Providers</h3>
              <ul className="list-disc list-inside ml-4 space-y-2">
                <li><strong>Firebase (Google):</strong> For user authentication and database services</li>
                <li><strong>Black Forest Labs:</strong> For AI image processing via FLUX.1 Kontext Pro</li>
                <li><strong>Lemon Squeezy:</strong> For payment processing and subscription management</li>
                <li><strong>Analytics Providers:</strong> For app performance and usage analytics</li>
              </ul>

              <h3 className="text-lg font-semibold text-gray-800 mb-2 mt-6">Legal Requirements</h3>
              <p>We may disclose your information if required to do so by law or in response to:</p>
              <ul className="list-disc list-inside ml-4 space-y-2">
                <li>Legal process or government requests</li>
                <li>Protection of our rights, property, or safety</li>
                <li>Protection of our users or the public</li>
                <li>Investigation of potential violations of our terms of service</li>
              </ul>
            </Section>

            {/* Data Security */}
            <Section title="Data Security">
              <p>We implement appropriate technical and organizational measures to protect your personal information:</p>
              <ul className="list-disc list-inside ml-4 space-y-2">
                <li>Encryption of data in transit and at rest</li>
                <li>Secure API communications with authentication tokens</li>
                <li>Regular security audits and updates</li>
                <li>Access controls and monitoring</li>
                <li>Secure payment processing through certified providers</li>
              </ul>
              <p className="mt-4 p-4 bg-yellow-50 border border-yellow-200 rounded">
                <strong>Important:</strong> While we strive to protect your information, no method of transmission over the internet or electronic storage is 100% secure. We cannot guarantee absolute security of your data.
              </p>
            </Section>

            {/* Your Rights and Choices */}
            <Section title="Your Rights and Choices">
              <p>Depending on your location, you may have the following rights regarding your personal information:</p>
              <ul className="list-disc list-inside ml-4 space-y-2">
                <li><strong>Access:</strong> Request copies of your personal information</li>
                <li><strong>Correction:</strong> Request correction of inaccurate personal information</li>
                <li><strong>Deletion:</strong> Request deletion of your personal information</li>
                <li><strong>Portability:</strong> Request transfer of your data to another service</li>
                <li><strong>Objection:</strong> Object to processing of your personal information</li>
                <li><strong>Restriction:</strong> Request restriction of processing</li>
              </ul>
              
              <h3 className="text-lg font-semibold text-gray-800 mb-2 mt-6">How to Exercise Your Rights</h3>
              <p>To exercise any of these rights, please contact us at:</p>
              <div className="bg-gray-50 p-4 rounded border mt-2">
                <p><strong>Email:</strong> consult@pixel.co.zw</p>
                <p><strong>Subject Line:</strong> Privacy Rights Request - IconicMe App</p>
              </div>
            </Section>

            {/* Children's Privacy */}
            <Section title="Children's Privacy">
              <p>
                Our Service is not intended for children under 13 years of age. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe your child has provided us with personal information, please contact us immediately.
              </p>
              <p>
                If we discover that a child under 13 has provided us with personal information, we will delete such information from our systems promptly.
              </p>
            </Section>

            {/* International Data Transfers */}
            <Section title="International Data Transfers">
              <p>
                Your information may be transferred to and processed in countries other than Zimbabwe, including the United States and European Union, where our service providers are located. These countries may have different data protection laws than your country of residence.
              </p>
              <p>
                By using our Service, you consent to the transfer of your information to these countries. We ensure that such transfers are conducted in accordance with applicable data protection laws.
              </p>
            </Section>

            {/* Changes to Privacy Policy */}
            <Section title="Changes to This Privacy Policy">
              <p>
                We may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal requirements, or other factors. We will notify you of any material changes by:
              </p>
              <ul className="list-disc list-inside ml-4 space-y-2">
                <li>Posting the updated policy on our website and in our app</li>
                <li>Sending you an email notification (if you have provided your email address)</li>
                <li>Displaying a prominent notice in our app</li>
              </ul>
              <p className="mt-4">
                Your continued use of our Service after any changes indicates your acceptance of the updated Privacy Policy.
              </p>
            </Section>

            {/* Contact Information */}
            <Section title="Contact Us">
              <p>If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:</p>
              
              <div className="bg-gray-50 border rounded-lg p-6 mt-4">
                <h4 className="font-semibold text-gray-800 mb-3">Pixelspulse Private Limited</h4>
                <div className="space-y-2">
                  <p><strong>Email:</strong> consult@pixel.co.zw</p>
                  <p><strong>Website:</strong> <a href="http://iconicme.shop" className="text-blue-600 hover:underline">http://iconicme.shop</a></p>
                  <p><strong>App Website:</strong> <a href="https://iconicme.shop/" className="text-blue-600 hover:underline">https://iconicme.shop/</a></p>
                  <p><strong>Developer:</strong> Innocent Nyamusa</p>
                </div>
              </div>

              <p className="mt-4 text-sm text-gray-600">
                We will respond to your inquiry within 30 days of receipt.
              </p>
            </Section>
          </div>
        </main>

        {/* Footer */}
        <footer className="bg-white border-t">
          <div className="max-w-4xl mx-auto px-4 py-6">
            <div className="text-center text-gray-600">
              <p>&copy; 2024 Pixelspulse Private Limited. All rights reserved.</p>
              <p className="text-sm mt-2">Made with ❤️ in Zimbabwe</p>
            </div>
          </div>
        </footer>
      </div>
  );
};

export default PrivacyPolicyPage;